name: etrax_rescue_app
description: The official App of the eTrax|rescue project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # App Localizations
  flutter_localizations:
    sdk: flutter
  # Service locator
  get_it: ^4.0.2
  # Bloc for state management
  flutter_bloc: ^5.0.1
  # Value equality
  equatable: ^1.2.0
  # Functional programming features
  dartz: ^0.9.1
  # Local cache
  shared_preferences: ^0.5.7+3
  # QR scanner data source
  #qrscan: ^0.2.17
  # Internet connection checker
  data_connection_checker: ^0.3.4
  # For proper conversion of DateTime to string
  intl: ^0.16.1
  # Making requests to the API
  http: ^0.12.1
  # Location data Source
  background_location:
    git:
      url: git@github.com:yozoon/flutter_background_location.git
  auto_route: ^0.6.1
  flutter_i18n: ^0.16.2
  moor_flutter: ^3.1.0
  path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  build_runner: null
  auto_route_generator: ^0.6.0
  intl_translation: ^0.17.10

flutter:
  uses-material-design: true
  fonts:
  - family:  CustomMaterialIcons
    fonts:
     - asset: fonts/CustomMaterialIcons.ttf

flutter_intl:
  enabled: true
