name: Test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install lcov
        run: sudo apt-get install lcov
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.1'
      - run: flutter pub get
      - run: flutter test --coverage test
      - run: lcov --remove coverage/lcov.info 'lib/generated/*' -o coverage/lcov_new.info
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/lcov_new.info
