name: CI

on:
  push:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.gitversion.outputs.test }}
    steps:
    - id: step1
      run: echo "::set-output name=test::hello"
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.4
      with:
        versionSpec: '5.3.x'
    - id: gitversion
      name: Use GitVersion  
      uses: gittools/actions/gitversion/execute@v0.9.4
    - run: |
        echo "::set-output name=test::0.1.0"
    #${{steps.gitversion.outputs.nuGetVersion}}"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
